

name: SonaQube-Android

on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube Android Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '15'
        check-latest: true
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - run: ./gradlew sonarqube -Dsonar.host.url=${{secrets.SONARQUBE_HOST}} -Dsonar.login=${{secrets.SONARQUBE_TOKEN}} -Dsonar.projectName=SonarQube-Demo-Android
      working-directory: ./Android/SonarQubeDemoAndroid
