

name: SonaQube-dotNet

on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube dotNet Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '14'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use
    - run: dotnet new tool-manifest
    - run: dotnet tool install dotnet-sonarscanner
      working-directory: ./CSharp/TestCSharpSonarQube
    - run: dotnet sonarscanner begin /k:"SonarQubeSetup" /d:sonar.host.url="${{secrets.SONARQUBE_HOST}}" /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}" /n:SonarQube-Demo-dotNet
      working-directory: ./CSharp/TestCSharpSonarQube
    - run: dotnet build TestCSharpSonarQube.sln
      working-directory: ./CSharp/TestCSharpSonarQube
    - run: dotnet sonarscanner end /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}"
      working-directory: ./CSharp/TestCSharpSonarQube