

name: SonaQube-Java

on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube Java Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '14'
    - run: ./gradlew sonarqube -Dsonar.host.url=${{secrets.SONARQUBE_HOST}} -Dsonar.login=${{secrets.SONARQUBE_TOKEN}} -Dsonar.projectName=SonarQube-Demo-Java
      working-directory: ./Java/sonarqube-demo/