

name: SonaQube-PHP

on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube PHP Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '15'
        check-latest: true
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.10.0
    - run: composer require rogervila/php-sonarqube-scanner
    - run: composer require rogervila/php-sonarqube-scanner && ./vendor/bin/sonar-scanner -Dsonar.host.url=${{secrets.SONARQUBE_HOST}} -Dsonar.login=${{secrets.SONARQUBE_TOKEN}} -Dsonar.projectName=SonarQube-Demo-PHP
      working-directory: ./PHP/sonarqube-demo-php
    